### ISSUE TITLE
axios cookie

### ISSUE THREAD

**Issue by usb248** [nuxt-community/axios-module#333]
### What problem does this feature solve?

Handle cookie jar in order to automatically resend received cookies on every subsequent request (server-side).
Actually, axios doesn't resend cookie received by nuxt serverResponse.
It cause many problem in my nuxt app.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/axios-module/issues/c329">#c329</a>)</em></sub></div>

**Comment by rchl** [comment]
It might make sense to have an option to "Proxy response cookies" but I have a comment for your "temporary fix". You will lose cookies already set on `res` if you do it this way. You want to also append existing cookie headers taken from `res.getHeader('Set-Cookie')`.

**Comment by usb248** [comment]
@rchl  yes i know, but strangely res.getHeader('Set-Cookie') is always undefined even if i see double set-cookie in nuxt response in my browser to render the view and i don't understand why...so I make sure that the 'last one' Set-Cookie is always the right one... it's ugly, but it works for this moment

**Comment by usb248** [comment]
a solution : https://github.com/nuxt-community/express-template/blob/master/protected-ssr-api.md#create-middlewaressr-cookiejs ?

**Comment by SebastiaanYN** [comment]
I'm currently dealing with the same problem. My backend adds a Set-Cookie header to the response with a new access_token whenever it has expired. This causes issues with SSR because they aren't forwarded to the client.

I've been working around this issue so far by making requests that require authentication from the client, but this takes away the smoothness of SSR.

An issue with the solution provided above is that on subsequent requests Axios might also need to access the new cookies. The ideal solution would be to mimic the behavior of browsers when dealing with cookies.

A possible solution I've been considering is to have a server-side plugin that updates the Axios cookies, and the Set-Cookie header on the response, whenever a Set-Cookie header is received.
```js
export default function ({ $axios, res }) {
  $axios.onResponse((response) => {
    // get the set-cookie header from the response
    const setCookies = response.headers['set-cookie'];

    if (setCookies) {
      // parse the cookies axios uses
      const cookies = parse($axios.defaults.headers.common.cookie);

      // add cookies from setCookies to cookies
      // set $axios.defaults.headers.common.cookie equal to the new cookie header

      // merge the existing Set-Cookie header with setCookies
      // set the cookies on the response, so the client gets them back
      res.setHeader('Set-Cookie', setCookies);
    }
  });
}
```

One possible issue with this solution is that it would proxy all cookies. So a potential filter could be added to not proxy cookies such as `x-powered-by`, `x-ratelimit-limit`, `x-ratelimit-remaining`, and others.

It would be nice to have this as an option, so SSR can be used to the fullest, without worrying about cookies not syncing.

**Comment by usb248** [comment]
@SebastiaanYN :
`const cookies = parse($axios.defaults.headers.common.cookie);` you do anything with `cookies` variable.
What's the point ?

**Comment by SebastiaanYN** [comment]
> It's not cookies ....

You're right, ignore that.

I think I managed to get a working plugin that updates cookies for Axios, and merges them on the response object. This allows sequential requests to have the correct cookies.
```js
// plugins/ssr-cookie-proxy.js
import { parse as parseCookie } from 'cookie';

function parseSetCookies(cookies) {
  return cookies
    .map(cookie => cookie.split(';')[0])
    .reduce((obj, cookie) => ({
      ...obj,
      ...parseCookie(cookie),
    }), {});
}

function serializeCookies(cookies) {
  return Object
    .entries(cookies)
    .map(([name, value]) => `${name}=${encodeURIComponent(value)}`)
    .join('; ');
}

function mergeSetCookies(oldCookies, newCookies) {
  const cookies = new Map();

  function add(cookie) {
    const name = Object.keys(parseCookie(cookie))[0];
    cookies.set(name, cookie);
  }

  oldCookies.forEach(add);
  newCookies.forEach(add);

  return [...cookies.values()];
}

export default function ({ $axios, res }) {
  $axios.onResponse((response) => {
    const setCookies = response.headers['set-cookie'];

    if (setCookies) {
      // Combine the cookies set on axios with the new cookies and serialize them
      const cookie = serializeCookies({
        ...parseCookie($axios.defaults.headers.common.cookie),
        ...parseSetCookies(setCookies),
      });

      $axios.defaults.headers.common.cookie = cookie; // eslint-disable-line no-param-reassign

      // If the res already has a Set-Cookie header it should be merged
      if (res.getHeader('Set-Cookie')) {
        const newCookies = mergeSetCookies(
          res.getHeader('Set-Cookie'),
          setCookies,
        );

        res.setHeader('Set-Cookie', newCookies);
      } else {
        res.setHeader('Set-Cookie', setCookies);
      }
    }
  });
}
```

And then register it in `nuxt.config.js`
```js
plugins: [
  { src: '@/plugins/ssr-cookie-proxy.js', mode: 'server' },
],
```

**Comment by usb248** [comment]
Your code manage signed cookies too ? @SebastiaanYN

**Comment by SebastiaanYN** [comment]
It copies the cookies over, by name, without modifying the values. So I would expect it to work, but you'd have to test it to be 100% certain.

**Comment by pi0** [comment]
@SebastiaanYN Nice work! If you would like to make a PR adding it built-in supported it is more than welcome. Also, [this](https://github.com/nuxt-community/auth-module/blob/8c3a351250b77220122782a0f621af5b9001af22/src/core/storage.ts#L243) may you inspire for a one-liner update solution. (originally taken from express)

**Comment by usb248** [comment]
@SebastiaanYN  you forgive to return `response` in `onResponse` callback. it causes an `axios-retry`   crash for example.

**Comment by usb248** [comment]
Something seems to be wrong... i get duplicate set-cookie headers :
![image](https://user-images.githubusercontent.com/7659927/80915135-718a2380-8d50-11ea-8caf-78c463c0505e.png)

:/

**Comment by SebastiaanYN** [comment]
@pi0 I'll give it a go. The reason I don't directly concat the old cookies with the new is to prevent unnecessary headers. If you make multiple requests that all overwrite a certain cookie, that could increase the header size quite a bit. And it would then also come down to the order browsers read the headers, whether they set the right cookies.

@usb248 I think this is caused by the `getHeader` functions returning either a `string` or a `string[]`. In this case, I only worried about `string[]` so it only works for multiple `Set-Cookie` headers. This can probably be fixed by having an arrayify function that is called on the headers.

**Comment by usb248** [comment]
@SebastiaanYN  `res.getHeader('Set-Cookie')` return `undefined` in my code (even when duplicate headers)

**Comment by SebastiaanYN** [comment]
That's strange. I don't know what could cause that. As far as I know `res.getHeader` it just the [`Response#getHeader`](https://nodejs.org/api/http.html#http_response_getheader_name) function from Node itself. It should only return `undefined` if there's no cookie with that name.

**Comment by usb248** [comment]
yes... i don't know why too. maybe @pi0  ?

duplicate headers occurs on first call (when there is no session cookie) on a route which has an axios SSR request. nuxt response + axios response. I have for example a get axios request in my nuxtServerInit which start an anonyme user session.
Problem still here with `arrayify` function

**Comment by pi0** [comment]
> res.getHeader('Set-Cookie')

Maybe can try `'set-cookie`? (node makes all headers lower-case)

**Comment by usb248** [comment]
The same ... :/

**Comment by usb248** [comment]
The problem seems to come from nuxt:
ouput => `[Object: null prototype] {}`
```
export default function ({ $axios, res }) {
  console.log(res.getHeaders())
   ....
})
```
`'~/plugins/proxy-cookies-ssr.server.js',`

**Comment by pi0** [comment]
@usb248 Browser cookies are already loaded into `headers.common.cookie` via [req.headers](https://github.com/nuxt-community/axios-module/blob/dev/lib/plugin.js#L201). For Axios response cookies they are in `response.headers['set-cookie']` You can follow #358 implementation :)

**Comment by usb248** [comment]
> BTW res.getHeader() is probably called to early in your example

So how to get header at the right moment :satisfied: @pi0  ?

**Comment by hamid159** [comment]
> ```js
> cookies.set(name, cookie);
> ```

@SebastiaanYN  You're coping only cookie value here. but it should set other attributes of cookies too e.g, expiry, path, httponly etc.
It should be 
```js
cookies.set(name, setCookie);
```
